spring:
  output:
    ansi:
      enabled: ALWAYS
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: true
server:
  port : 8081
